.github/workflows/on-push-feature-branch.yaml, .github/workflows/on-push-main-branch.yaml, .github/workflows/on-tag.yaml, .github/workflows/publish.yaml, .github/workflows/tests.yaml, api/.dockerignore, api/poetry.lock, api/pyproject.toml, docker-compose.yml, web/.dockerignore, web/.eslintrc.js, web/Dockerfile
Need proper container registries to run CI all the way
Update CI workflows to use correct container registry
closes #16
=> feat: build and push images in ci

docs/tutorials/authentication.md
Some basics on how auth is setup and configured in the template repo
Add a new markdown document with a short tutorial on "Authentication and Authorization"
closes #21
=> feat: tutorial on authentication

.gitignore, docs/getting-started/inital-setup.md, web/Dockerfile
Add some documentation and extra check on yarn install in Dockerfile
=> doc: update documentation on Yarn 2 usage

.github/workflows/release-please.yml
Enable auto-generated changelings based on conventional commits
Creates a release-PR with changelog, when merging release-pr new tag and changelog.md is changed
=> feat: autogenerate release changelog

.github/workflows/on-push-main-branch.yaml, radixconfig.yaml, web/src/api/TodoAPI.tsx
* Set correct base path for generated typescript clients
* Set correct OAUTH_CLIENT_ID and OAUTH_AUDIENCE in radix config
* Make it run correctly in Radix
=> Correct base path

.github/workflows/on-push-main-branch.yaml, api/Dockerfile, api/poetry.lock, radixconfig.yaml
* The API crashes, need to fix that
* Downgrade to not using slim (this will be fixed later)
* Adding MongoDB to radix (this may be moved to Azure later)
=> Api crashes

documentation/docs/running/02-configure.md, documentation/docs/running/03-starting-services.md
* Add missing environment variable descriptions
* Adding description to environment variables used
=> docs: add missing environment variables descriptions

documentation/docs/contribute/development-guide/coding/extending-the-api/02-adding-entities.md, documentation/docs/contribute/development-guide/coding/extending-the-api/adding-data-providers/01-clients.md, documentation/docs/contribute/development-guide/coding/extending-the-api/adding-data-providers/03-repositories.md, documentation/docs/contribute/development-guide/coding/extending-the-api/adding-features/01-controllers.md, documentation/docs/contribute/development-guide/coding/extending-the-api/adding-features/02-use-cases.md
* Inform how to test code
* Add description on how to test controllers, use cases, entities, repositories, and clients.
=> docs: add how to tests components

api/src/data_providers/clients/ClientInterface.py, api/src/data_providers/clients/mongodb/MongoDatabaseClient.py, api/src/data_providers/repositories/TodoRepository.py, api/src/features/todo/use_cases/delete_todo_by_id.py, api/src/features/todo/use_cases/get_todo_by_id.py, api/src/tests/integration/features/health_check/test_health_check_feature.py, api/src/tests/integration/features/todo/test_todo_feature.py, api/src/tests/integration/features/whoami/test_whoami_feature.py, api/src/tests/unit/features/todo/use_cases/test_add_todo.py, api/src/tests/unit/features/todo/use_cases/test_delete_todo_by_id.py, api/src/tests/unit/features/todo/use_cases/test_get_todo_all.py, api/src/tests/unit/features/todo/use_cases/test_get_todo_by_id.py, api/src/tests/unit/features/todo/use_cases/test_update_todo.py, documentation/docs/about/concepts/02-use-case.md
* Pytest fixtures are missing types
* Delete is not throwing not found exceptions correctly
* Add types to fixtures
* Check that delete is performed or return not found exception if not
=> fix: add types to fixtures

documentation/src/pages/index.module.css, documentation/src/pages/index.tsx
The feature list wasn't symmetrical. Just barely off-center.
Styles the feature list a bit (adds a hover effect etc.)
None.
=> docs: style feature list

documentation/docs/about/02-overview.md, documentation/docs/contribute/development-guide/coding/01-architecture.md, documentation/docs/contribute/development-guide/coding/extending-the-api/adding-features/01-controllers.md, documentation/docs/contribute/development-guide/coding/extending-the-api/index.md
* Adding some more text to the Clean Architecture introduction section
* Added som more input to the layers and why they are divided into four layers
=> docs: add more text to clean architecture section

documentation/docs/contribute/development-guide/coding/extending-the-api/adding-features/index.md
* How to register a feature
* Adding code section that shows how to add a router to the app
Looks like this
Further down...
=> docs: how to register a feature to the app

documentation/docs/about/01-introduction.md
* Remove key features from introduction since they are on entry page (no need du duplicate)
* Remove key features
=> docs: remove key features

documentation/docs/contribute/development-guide/01-setup.md, documentation/docs/contribute/development-guide/05-publishing.md
- To provide an overview of the pre-commit hooks used in this repository
- To provide an overview of the CICD pipeline and the tasks that are run
Adds documentation on pre-commit hooks and the CICD pipeline
- Resolves #116
- Resolves #117
=> Docs: Overview of pre-commit hooks and the CICD pipeline

.vscode/settings.json, api/src/entities/TodoItem.py, api/src/features/todo/todo_feature.py, api/src/features/todo/use_cases/add_todo.py, api/src/features/todo/use_cases/delete_todo_by_id.py, api/src/features/todo/use_cases/get_todo_all.py, api/src/features/todo/use_cases/get_todo_by_id.py, api/src/features/todo/use_cases/update_todo.py, api/src/tests/integration/features/todo/test_todo_feature.py, api/src/tests/unit/data_providers/repositories/test_TodoRepository.py, api/src/tests/unit/entities/test_todo_item.py, api/src/tests/unit/features/todo/conftest.py, api/src/tests/unit/features/todo/use_cases/test_add_todo.py, api/src/tests/unit/features/todo/use_cases/test_delete_todo_by_id.py, api/src/tests/unit/features/todo/use_cases/test_get_todo_all.py, api/src/tests/unit/features/todo/use_cases/test_get_todo_by_id.py, api/src/tests/unit/features/todo/use_cases/test_update_todo.py
If @eoaksnes has made a todo to feed his dog, it's weird that it shows up on my todo-list.
Makes todos personal, and makes the api serve them depending on who's logged in.
It's worth discussing whether this should "go deeper" than just the use-cases. Maybe the repos should care, or maybe even the client?
Closes #129
=> feat: user-specific todos!

documentation/docs/contribute/development-guide/01-setup.md
Requested in #134.
Rewrites `01-setup.md`'s `Yarn PnP in VSCode` chapter.
Closes #134.
=> docs: rewrite 01-setup Yarn PnP in VSCode

.github/workflows/publish-docs.yaml
- External actions with write permissions is a security risk
- Replace the external action with a few git commands
none
=> refactor(ci): remove crazy-max external action

.github/workflows/deploy.yaml
Missing correct permissions
Adds necessary permissions
=> ci: correct permissions

.github/workflows/deploy.yaml
* Specify correct context 
* Use playground instead of production radix cluster
=> ci: specify playground context

.github/workflows/codeql.yml, .github/workflows/deploy.yaml, .github/workflows/generate-changelog.yaml, .github/workflows/on-manual-label-importer.yml, .github/workflows/on-push-main-branch.yaml, .github/workflows/publish-docs.yaml, .github/workflows/release-production.yaml
I believe this is how workflows should be linted. Writing them differently creates noise in other consecutive PRs when developers have enabled lint fixing on save.
Write summary of what this pull request changes if needed.
=> refactor(workflow): Fix linting errors

web/src/common/components/IconButton.tsx, web/src/features/todos/todo-list/TodoItem.styled.tsx, web/src/features/todos/todo-list/TodoItem.tsx
Minor changes/refactoring to reduce complexity and repeated code in `TodoItem.tsx`.
=> refactor: reduce complexity of TodoItem

web/src/common/components/Header.tsx, web/src/common/components/Popover.tsx
Adds Popover component to reduce complexity of `Header.tsx`
=> feat: popover

web/src/hooks/useTodoAPI.tsx
Memoizes todoAPI. Also, removed a unused export. I don't think it makes sense to use it to access the API anymore.
#199
=> refactor: memoize api

.github/labels.yml, .pre-commit-config.yaml, CHANGELOG.md, api/pyproject.toml, api/src/authentication/authentication.py, api/src/tests/unit/features/todo/use_cases/test_delete_todo_by_id.py, documentation/docs/contribute/02-ground-rules.md, documentation/docs/contribute/development-guide/05-publishing.md, documentation/docs/contribute/development-guide/coding/01-architecture.md, documentation/docs/contribute/development-guide/coding/extending-the-api/adding-features/03-securing-endpoints.md
There were typos in the repository
Fixes those typos + adds `codespell` pre-commit hook to catch typos earlier in the future
N/A
=> style: fix typos + add codespell pre-commit hook

.github/workflows/on-pull-request.yaml, .github/workflows/on-push-main-branch.yaml, .github/workflows/on-weekly.yaml
* Mismatch between filename and what is used in code for workflow
* Point to correct codeql workflow file
=> ci: call correct workflow file

api/src/app.py, api/src/common/exception_handlers.py, api/src/common/exceptions.py, api/src/common/responses.py, api/src/features/todo/todo_feature.py, api/src/tests/conftest.py, api/src/tests/integration/common/test_exception_handler.py, api/src/tests/unit/common/test_exception_handler_integration.py
This pull request is needed because the old ´create_response´ wrapper was a mess
Use starlettes exception handlers instead of custom wrapper solution for exception handling
=> Feat: new exception handling

.github/CODEOWNERS
To automatically request review from the relevant people. Easier for external (and internal) contributors
Create two sub-teams under teams-hermes, for backend and frontend
=> chore: add Codeowners

.pre-commit-config.yaml, api/poetry.lock, api/pyproject.toml, api/src/app.py
This pull request is needed because the ´pre-commit´ failed for me with pre-commit version <3
- updated ´pre-commit´ requirement
- Use ruff implementation of isort and bandit
- bump hook versions
=> ci: update pre commit

.pre-commit-config.yaml, api/pyproject.toml, api/src/app.py, api/src/authentication/authentication.py, api/src/authentication/mock_token_generator.py, api/src/authentication/models.py, api/src/common/exception_handlers.py, api/src/common/exceptions.py, api/src/common/middleware.py, api/src/config.py, api/src/data_providers/clients/client_interface.py, api/src/data_providers/clients/mongodb/mongo_database_client.py, api/src/features/todo/entities/todo_item.py, api/src/features/todo/repository/todo_repository.py, api/src/features/todo/repository/todo_repository_interface.py, api/src/features/todo/todo_feature.py, api/src/features/todo/use_cases/get_todo_all.py
This pull request is needed because of....
- Enable mypy strict mode
- Add types from 3rd party dependencies to mypy
- Add stronger typing
=> refactor: improve type-strictness

web/src/App.tsx
- using deprecated login function
- updated to new logIn function
=> chore: use correct login function

.github/dependabot.yml, .github/workflows/codeql.yaml, .github/workflows/deploy-to-radix.yaml, .github/workflows/generate-changelog.yaml, .github/workflows/label-importer.yaml, .github/workflows/on-push-main-branch.yaml, .github/workflows/publish-docs.yaml, .github/workflows/publish-image.yaml, .github/workflows/rollback.yaml, .github/workflows/tests.yaml, .pre-commit-config.yaml, api/pyproject.toml
Many of the github actions used are using old, or even deprecated, versions.
Updates versions.
closes #277
=> ci: update action versions

api/src/authentication/authentication.py
Want to be able to use api when Authorisation is disabled
Add check on AUTH_ENABLED and use default_user if disabled
=> fix: allow auth disabled -> default to default_user

web/src/features/todos/todo-list/TodoList.styled.tsx
Just trying to clear out old issues
- #147
Add spacing between list items
Closes #147
=> fix: add spacing between list items

docker-compose.yml
=> chore: use ghcr.io for all images in docker-compose.yml and update mongo image to 7.0.17

RUNBOOK.md
Closes #298.
Note that this runbook is a copy of Void's runbook, but with any mention of Void removed. 
It naturally doesn't really work on its own, and should be reviewed as a template for future usage.
=> docs: add RUNBOOK.md

.env-template
This pull request is needed because of....
a mistake we made by deleting the old one 😅
Re-adds an actual app-reg, allowing us to log in.
Closes #299
=> chore: add new app-reg to `.env-template`

web/src/contexts/TodoContext.tsx, web/src/features/todos/todo-list/TodoItem.tsx, web/src/features/todos/todo-list/TodoList.tsx, web/src/hooks/useTodoAPI.tsx
Remove unnecessary functions and arguments, introduce a type alias for Todo items, and rename variables for improved clarity in the Todo context and API.
=> refactor: Todo context and API for clarity and consistency

documentation/docusaurus.config.js, documentation/package.json, documentation/yarn.lock
=> chore: update docs dependencies

api/src/features/todo/todo_feature.py, web/src/api/generated/index.ts, web/src/api/generated/models/AddTodoResponse.ts, web/src/api/generated/models/GetTodoByIdResponse.ts, web/src/api/generated/models/User.ts, web/src/api/generated/services/HealthCheckService.ts, web/src/api/generated/services/TodoService.ts, web/src/api/generated/services/WhoamiService.ts, web/src/hooks/useTodoAPI.tsx
It was bugging me that it was called `TodosService`
=> refactor: make the router tagged with "todo" instead of "todos" to ensure "TodoService" name

web/src/features/todos/todo-list/TodoItem.tsx, web/src/features/todos/todo-list/TodoList.tsx, web/src/hooks/useTodoAPI.tsx
Refactor the Todo API interactions to use async/await for better readability and error handling. Introduce a centralized error handling function and move dispatch calls into the API functions for improved state management.
=> Refactor Todo API handling with async/await and error management

api/pyproject.toml
=> chore: enable mypy strict mode
