.github/workflows/publish-docs.yaml
README.md
doctave.yaml

* After going public we need to set base path for docs in GH pages
* Set base_path to  /template-fastapi-react

fix: set correct base path for docs

---

docker-compose.override.yml
docker-compose.yml

_Adding env_file-property to service-declarations in `docker-compose.yml` stops `docker-compose up` from running without a `.env`-file present._
This pull request is needed because of a bug happening if there is no `.env`-file present when `docker-compose up` is run the first time. If so, the `data/`-folder will contain incompatible data, meaning it will have to be deleted before another attempt is made. 
As there are no/few cases where _no_ environment variables are in use, a simple fix is to require it in `docker-compose.yml`.
Adds the bottom two lines to each service declaration in ~`docker-compose.yml`~.
EDIT: Changes moved to `docker-compose.override.yml`.  
```yml
services:
my-app:
env_file:
- .env
```
None.

fix: env_file in docker-compose.yml

---

documentation/docs/contributing/development-guide/coding/01-architecture.md

The plantUML diagrams are now horizontal, not vertical. That saves us a lot of real-estate on the screen when viewing. 
I got this approved by @hakoneriksson, although @eoaksnes and @paultrygs claimed it was a war-crime to show C4-diagrams horizontally. 
(I had to zoom out in my browser to see it all)
None.

docs: turn puml diagrams sideways

---

api/Dockerfile

* The API does not work in Radix
* Seems that Radix has problems with using Docker Entrypoint, need to specify path to init script in CMD

Fix run in radix

---

documentation/docs/contributing/01-ground-rules.md

* Provide example of git commit messages
* Add  3 examples of how to write git commit messages

docs: add examples of git commit messages

---

api/src/tests/unit/features/todo/conftest.py

* We don't need the old client mock 
* Use in unit tests new test client instead of the old mock

refactor: remove old client mock

---

documentation/docs/contribute/development-guide/coding/01-architecture.md

* The diagrams generated are too small to see for an old person (like me)
* Remove `left to right direction` option

docs: revert left to right for diagrams

---

documentation/docs/contribute/development-guide/01-setup.md
documentation/docs/contribute/development-guide/03-testing.md

* Use tabs to show different options in nice way
* Replace details/summary with tabs

docs: use tabs to show platform specific options

---

documentation/docusaurus.config.js

* Add link to open API docs 
* Adding link to header

docs: add link to API docs

---

documentation/docs/contribute/development-guide/coding/extending-the-api/adding-features/01-controllers.md

* Make text consistent, only use request and response models (not request object etc)
* Small re-write of intro to controllers

docs: re-write intro to controllers

---

documentation/docusaurus.config.js

* Add link to easy open the demo
* Add link to demo in top menu

docs: add link to demo

---

web/src/router.tsx

BrowserRouter is recommended for a web projects [(https://reactrouter.com/en/main/routers/picking-a-router)](https://reactrouter.com/en/main/routers/picking-a-router#web-projects)
Now the web app follows the recommend setup from the react-router docs: https://reactrouter.com/en/main/routers/create-browser-router
Substitute HashRouter with BrowserRouter
closes #45

chore: substitute HashRouter with BrowserRouter in web app

---

web/src/features/todos/todo-list/TodoList.tsx
web/src/hooks/useTodos.tsx

Make useTodos simpler to use. Now, the user don't have to remember the order of things returned from useTodos
make useTodos simpler to use
none

fix: make useTodos simpler to use

---

.github/workflows/codeql.yml
.github/workflows/publish.yaml

To fix incorrect references to the `master` branch
Updates refs to `master` => `main`

fix (cicd): use correct branch name (`master` => `main`)

---

.github/workflows/tests.yaml

This pull request is needed to ensure our changes does not break the docs build
Creates a new test. It will check out the repo and build the docs.
In the template, there are several cases there the documentation displays parts of code from outside of the documentation folder, and if that code is not found the build will fail. If the template had not done that, we could have run a check to see if anything in the docs folder had changed and only run the time consuming build if it had. I've therefore left such a functionality in the comments, in case it might become useful for other repos using this template.

test(docs): Add testing of docs

---

docker-compose.override.yml

We have a bug on some computers, which causes the mongodb to not come online when running `docker compose up --build` _after_ initial setup. 
I know for a fact that this affects M1 macs using docker with VirtioFS enabled. I need to enable VirtioFS because it increases filesystem performance drastically in docker.
It adds a docker volume called `database`, and rather than mounting the `db`-container's `/data/db` to a local folder, we just mount it to the volume.
Note: This means you won't be able to read the db storage files in you local filesystem.
None

build: fix mac m1 virtiofs docker problem

---

documentation/docs/contribute/development-guide/coding/extending-the-api/index.md
documentation/docs/contribute/development-guide/coding/extending-the-web/index.md

* Add configuration section to how to extend the API
* Add text about configuration section for API

docs: add configuration section to  "extending the API" page

---

web/src/features/todos/todo-list/TodoList.tsx

It's natural that hitting `enter` when writing a todo should clear the input field. It didn't before.
It's natural that hitting `enter` when writing a todo should clear the input field. Now it does.
None.

feat(web): clear input on add-todo

---

web/src/features/todos/todo-list/TodoList.tsx

This pull request is needed because I forgot to add this one line in yesterday's related PR #125.
Adds a `value={value}` line. 
Only that @eoaksnes notified me. No formal issue.

fix(web): adding todo item now clears input

---

web/package.json

React hot reloading didn't work with docker-compose. Setting `WDS_SOCKET_PORT=80` allows react to hot-reload properly when using docker, because the port is exposed.
None.

chore(dev): make CRA use port 80 for websocket

---

web/package.json

Some of the eslint rules are configured to give warnings, but won't cause pre-commit check to fail. Checking for warnings can be useful during development, and it's easier to do so by running `yarn lint` now that the script is added.

chore: add script to run eslint

---

web/src/common/components/Header.tsx
web/src/features/todos/todo-list/TodoItem.tsx

EDS allows [two methods to using their icons](https://eds-storybook-react.azurewebsites.net/?path=/docs/icons-icon--introduction#usage):
1. First add the icons to the "loaded set" (make sure to only do this once!) and use the `name=""` prop to use it (no typechecking or autocomplete here).
2. Just import the icon and use the `data={}` prop.
The second method is simpler. Why not use it?
Replaces usage of `name=""` prop with `data={}` prop.
--- 
Note: I'm not sure how this affects e.g. loading times. EDS provides no information on potential differences between the two methods, and from their presentation they are equal. 
As far as I understand, the icons are loaded into the javascript bundle in both cases, and therefore I can't imagine there should be any difference in performance.
Feel …

refactor: use <Icon> data prop instead of name

---

.github/workflows/release-please.yml
api/pyproject.toml
api/src/app.py

The flow of updating api-version in openAPI spec was unecessary complicated
- Api version (in openAPI spec) is now set directly by release-please
- remove toml as extra dependency

refactor: remove pyproject.toml parsing with extra-files

---

api/Dockerfile
api/pyproject.toml

New python version released
Add support for python 3.11, changed docker image to slim-version (recommended by Snyk: https://snyk.io/blog/best-practices-containerizing-python-docker/)

build: bump python version to 3.11

---

web/src/hooks/useTodoAPI.tsx
web/src/hooks/useTodos.tsx

Fixes violation of exhaustive-deps rule by separating the api in a custom hook that will stay in sync with token change.

fix: add missing dependency without causing infinite loop of re-rendering

---

.pre-commit-config.yaml

Flake switched from gitlab to github today - so we need to do this. This PR fixes pipeline issues on other PRs (like #146). 
None.

build(ci/cd): update flake8 repo location

---

.github/workflows/generate-changelog.yaml
.github/workflows/tests.yaml

The `set-output` command in the GitHub Actions workflows, [is about to become deprecated](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).
To change from the 
```sh
echo "::set-output name=tag-ref::TAG_REF"
```
to the new
```sh
echo "tag-ref=$TAG_REF" >> $GITHUB_OUTPUT
```
stanza

Fix: replace deprecated output definition

---

.pre-commit-config.yaml

This pull request is needed because pre-commit hooks are quite outdated, and are not updated by Snyk/Dependabot
Bump pre-commit hooks with `pre-commit autoupdate`

ci: bump pre-commit hooks

---

.github/workflows/release-please.yml
.pre-commit-config.yaml

This pull request is needed because release-please, as default, only updates/creates a release PR if the commit is of type feat or fix. That can be problematic for low-intensity projects that mostly just updates packages.
The PR adds a json string that would pick up all the common commit types. The point is to demonstrate how this can be done and provide a reasonable default.

ci: Include all commit types in changelog

---

.github/workflows/publish-docs.yaml

This pull request is needed because publish docs workflow fails
Adds github_pages_branch as env variable

ci: Fix bug in publish docs

---

.github/workflows/deploy.yaml
.github/workflows/release-please.yml
.github/workflows/release-production.yaml

Machine user token are deprecated.
Login as the service principal with request of an access token, which can be used with Radix CLI/Radix API.

Login as the service principal to request an access token

---

.github/workflows/on-push-main-branch.yaml

* Main branch fails
* Remove secret as input to deploy, since this is not used anymore

ci: remove secret as input to reusable workflow

---

CONTRIBUTING.md

To lower the threshold for contributions.
Previous link 404's.
Change link to contributing page in `CONTRIBUTING.md` to correct page.
None

Fix dead link in `CONTRIBUTING.md`

---

web/src/common/components/VersionText.tsx

This pull request is needed because we don't want to break **SOLID** principles. (Single Responsibility Principle)
* Throws a more meaningful error if there's problems reading the version file
* Adds `type CommitInfo` to get better documentation of the code
* Separates responsibilities - rendering of the JSX component and fetching data
* Increases testability of `VersionText.tsx`, reducing the need of conditional rendering (potentially slightly better performance), making the code adaptable to changes.
Ideally, I'd like the component to be even more independent of the fetch, but after I added the new error message, I noticed that the endpoint threw 404, and it'd be nice to see the what a successful response looked like. I think it makes sense to try to fix that first, and then continue …

refactor: move fetch-logic to custom hook to separate responsibilities

---

.github/workflows/create-release-pr.yaml
.github/workflows/deploy-to-radix.yaml
.github/workflows/on-push-main-branch.yaml
.github/workflows/publish-image.yaml
.github/workflows/rollback.yaml
.github/workflows/tests.yaml

This pull request is needed because sometimes we might publish buggy code to prod and will need to roll back to a stable version. We might be in a hurry, so it's nice to have the rollback functionality ready
- Adds a rollback workflow
- Update the publish-image workflow to add release tags to the images as well as "production"
- Refactor and document
Closes #153

ci: Add rollback workflow

---

web/src/features/todos/todo-list/TodoItem.tsx
web/src/features/todos/todo-list/TodoList.tsx
web/src/hooks/useTodoAPI.tsx

This pull request is needed because separation of concerns 😄
Moves dependency to api from the jsx-components to the custom hook `useTodoAPI`. Fetching and state handling were previously nested together in `useTodos` until state handling got separated in #193. Fetch-logic got temporarily moved to the components that consumed them until this PR.
#193

refactor: move dependency to API to useTodoAPI hook

---

.pre-commit-config.yaml
api/.flake8

only need to specify pre commit settings related to python in as few places as possible
use pre-commit hook settings from pyproject.toml (and .flake8 file) and remove them from pre-commit-config.yaml
closes #189

refactor: use settings in pyproject.toml for pre commit hooks related to python

---

web/src/common/components/Header.tsx
web/src/common/components/IconButton.tsx

Cleans up the code in `Header.tsx`:
- Uses `IconButton` introduced in #201 to remove repeated code in `Header`
- Forwards ref to `IconButton` to be able to anchor Popover (#204)
- Removes conditional render in `Header`
This piece of code renders `Unauthenticated` and then re-renders to `Logged in as ..` without requiring any log in in between. I had a look at the auth config in `App.tsx`, and it seems you shouldn't be able to render `Header` at all if you're not already authenticated. Meaning this conditional render is kinda redundant and will only cause unnecessary re-renders.
```typescript
{tokenData ? (
<>
<Typography>Logged in as {username}</Typography>
<Button
variant="ghost_icon"
aria-label="Log out"
title="Log out"
onClick={logOut}
>
<Icon data={log_out} title="Log out" /> …
```

refactor: header

---

api/poetry.lock
api/pyproject.toml
api/src/init.sh
radixconfig.yaml

This pull request is needed too align our deployment with fastapi recommendations https://fastapi.tiangolo.com/deployment/docker/. When running fastapi in kubernetes cluster, only one uvicorn worker per pod is recommended. This way the gunicorn load balancer becomes redundant. 
- Remove gunicorn, only run one worker per container. 
- Add horizontal scaling in radix

fix: replace gunicorn with horizontal scaling

---

api/src/app.py
api/src/common/middleware.py

This fixes an issue caused by our middleware, that was implemented in a way making them incompatible with Starlettes BackgroundTasks (see: https://github.com/encode/starlette/issues/919).
The refactored middleware is now written as a "pure ASGI middleware" (see: https://www.starlette.io/middleware/#pure-asgi-middleware)

refactor: rewrite logger middleware to be a 'pure ASGI' middleware

---

.github/workflows/publish-image.yaml

regression from 3c6ebd9ba0964d2beae3762061bb82211013a8b6
#206 changed how the images were built, by removing the node / web image in production and replacing it with NginX.
I didn't make the necessary changes in `.github/workflows/publish-image.yaml` to reflect this change.
Makes sure the previous `web` component is removed / renamed in favour of the `nginx` component.
In principle, the logic for creating the `web` image was moved to the `nginx` image. In practice, the `web` image was renamed, and adjusted slightly, while the old `nginx` image was removed.

The template no longer use the node image in production

---

api/pyproject.toml
api/src/pytest.ini
api/src/tests/conftest.py
web/generate-api-typescript-client-pre-commit.sh

This pull request is needed because the wrong typescript client got pushed by accident. Avoid this mistake in the future
Check that the correct openapi spec is used to generate the typescript client

ci: avoid future mistake

---

api/poetry.lock
api/pyproject.toml
api/src/app.py
api/src/authentication/authentication.py
api/src/common/exception_handlers.py
api/src/common/exceptions.py
api/src/common/middleware.py
api/src/common/telemetry.py
api/src/features/health_check/health_check_feature.py
api/src/features/todo/todo_feature.py
api/src/features/todo/use_cases/get_todo_all.py
api/src/features/whoami/whoami_feature.py
api/src/tests/integration/mock_authentication.py
web/src/api/generated/core/request.ts

OpenSensus is deprecated and should be migrated to OpenTelemetry
To support correct tracing, exceptions in the api routers should be handled differently
- Replace OpenSensus with OpenTelemetry
- Replace existing exception handling with custom route class `ExceptionHandlingRoute` that wraps requests in try/except to capture and handle excpetions on our own
- Add `cryptography` as a separate dependency as it was included with OpenSensus
Closes #251

fix: replace OpenSensus with OpenTelemetry and fix exception handling

---

api/Dockerfile
api/poetry.lock
api/pyproject.toml
web/Dockerfile

Old packages needs updating
Bump following dependencies:
- python
- fastapi
- pydantic
- httpx
(dev)
- pytest

chore: bump python 3.10 -> 3.12

---

.github/workflows/deploy-to-radix.yaml
.github/workflows/on-push-main-branch.yaml
.github/workflows/publish-image.yaml
radixconfig.yaml
web/Dockerfile
web/src/auth.ts

Currently we only have two environments: test (dev) and prod. Adding a third staging / QA environment will serve as a buffer between the two environments to make production more stable.
- Add staging environment to radix that will be published on release
- Prod will be promoted to from staging manually in radix console
- Remove unnecessary AUTH_REDIRECT_URI environment variable

ci: add staging environment

---

IaC/app-registration.bicep
IaC/bicepconfig.json
IaC/exceptionEmailNotification.bicep
IaC/main.bicep
IaC/resources.bicep

Automatic setup of
- AppRegistration
- ResourceGroups
- ApplicationInsight
- LogAnalytics
- KeyVault
- postgres databases
Adds bicep files that can be deployed via `az cli`

ci: add bicep files for resource setup

---

web/nginx/environments/web.prod.conf

Fixes a bug where routes defined only in the SPA (react-router etc.) returns 404.
nginx must return index.html for all files not found (assets, chunks, etc.)

fix/404 on all react-router paths

---

.github/dependabot.yml

We don't need that frequent updates in the template
Update the interval from weekly -> monthly

chore: setup dependabot to run monthly

---

.pre-commit-config.yaml

Run tests from the test folder so that test data can be be imported consistently
update pre-commit hook to run tests in the test folder

fix: run tests from the src folder

---

.github/workflows/generate-changelog.yaml
web/nginx/config/security.conf
web/nginx/environments/web.dev.conf
web/nginx/environments/web.prod.conf
web/nginx/sites-available/default.conf
web/package.json
web/vite.config.mts
web/yarn.lock

- `add_header` directive in nginx only actually included on the innermost level, causing `security.conf` to be left out
- refrain from using `unsafe-inline` on scripts by instead whitelisting inline scripts using SRI (subresource integrity), that allows scripts to be run only if the hash of their content matches the computed hash in the meta tag
Move CSP out of `security.conf` into vite plugin that is able to generate CSP in the DOM as a meta tag and add SRI to allow the scripts we need to run
Closes #268

fix: use vite plugin to generate http-equiv meta tags for csp

---

web/vite.config.mts

Do not have to generate SRI locally. Conflicts with react reload script etc.
Disable SRI when running yarn start, only on yarn build

fix: disable csp locally

---

.github/workflows/generate-changelog.yaml

v3 is deprecated
update version to v4

chore(workflow): update upload artifact action to v4

---

.pre-commit-config.yaml
web/biome.json

Biome schema can match installed package version + update version used in pre-commit
#275

chore: biome match installed package version

---

.pre-commit-config.yaml
api/src/config.py
documentation/docs/contribute/development-guide/coding/extending-the-web/index.md
web/generate-api-typescript-client-pre-commit.sh
web/package.json

Some of the hooks in the pre-commit was running old versions.
Updates versions.
Additionally I changed the port in `yarn generate` command as it was pointing to 5001.
Furthermore, bashls had some suggestions to improving the script itself, so I applied those:
- "[SC2162] Read without -r will mangle backslashes"
- "[SC2086] Double quote to prevent globbing and word splitting"
- "[SC2005] Useless echo? Instead of `echo $(cmd)` just use `cmd`"
- "[SC2181] Check exit code directly with e.g. `if ! mycmd;`, not indirectly with $?."
- Added early exit if no changes are detected instead of using else.
Also had to do some fixes due to updated hooks detecting new errors.
Closes #276

ci: update pre commit hooks

---

web/src/features/todos/todo-list/TodoItem.styled.tsx
web/src/features/todos/todo-list/TodoItem.tsx

Console error logging about styled-components props forwarding unknown props to DOM
Use styled-component prefix on sc specific props

fix: avoid prop forwarding to dom using sc prefix

---

.github/workflows/codeql.yaml
.github/workflows/on-pull-request.yaml
.github/workflows/on-push-main-branch.yaml
.github/workflows/on-weekly.yaml

Codeql does not function properly.
Changes how codeql is called in actions. 
It needs a specific on.push hook, making it difficult to integrate into our workflows (due to how they are triggered). Therefore it is now run seperately on pushes and on pull requests to main.
None

ci: change how codeql is run

---

.github/dependabot.yml

To cover `documentation` folder for dependabot
Dependabot will now update dependencies in `documentation`

ci: Add `documentation` directory to dependabot
